#!/bin/bash
#
# helper script to execute porta

# check prerequisites
if [ ! -d "/usr/src/linux-headers-`uname -r`" ] ; then
  echo "ERROR: headers for `uname -r` not found"
  exit 1
fi
type docker >/dev/null 2>&1 || { echo >&2 "Can't find docker command."; exit 1; }

case $1 in
  "base")
    docker run \
      --rm \
      -v `which docker`:/usr/bin/docker \
      -v /usr/lib/libapparmor.so.1:/usr/lib/libapparmor.so.1 \
      --net=host \
      -e DOCKER_HOST=$DOCKER_HOST \
         ivotron/porta --action $@ > target.json
    ;;
  "tune")
    echo "" > parameters.json
    docker run \
      --workdir=/ \
      --rm \
      --privileged \
      -v /sys/kernel/debug:/sys/kernel/debug \
      -v /usr/src:/usr/src \
      -v /lib/modules:/lib/modules \
      -v `which docker`:/usr/bin/docker \
      -v /usr/lib/libapparmor.so.1:/usr/lib/libapparmor.so.1 \
      -v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1 \
      -v `pwd`/target.json:/target.json \
      -v `pwd`/parameters.json:/parameters.json \
      --net=host \
      -e DOCKER_HOST=$DOCKER_HOST \
         ivotron/porta --action $@
    ;;
  *)
    echo "Unknown action '$1'"
    ;;
esac
