---
  - name: ensure docker-engine is installed
    package:
      name: '{{ item }}'
      state: present
    become: true
    with_items:
    - docker-engine
    - curl

  - name: check if docker is statically linked
    command: ldd /usr/bin/docker
    register: docker_ldd
    ignore_errors: true

  - name: determine if we should install statically linked docker daemon
    set_fact:
      install_static_docker: '
        "not a dynamic executable" not in docker_ldd.stdout and
        install_statically_linked_docker | bool'

  - name: stop the docker daemon
    service:
      name: docker
      state: stopped
    become: true
    when: '"not a dynamic executable" not in docker_ldd.stdout'

  - name: get statically linked docker tarball
    command: curl -O https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz chdir=/tmp
    when: '"not a dynamic executable" not in docker_ldd.stdout'

  - name: untar statically linked docker
    command: tar xfz docker-latest.tgz chdir=/tmp
    when: '"not a dynamic executable" not in docker_ldd.stdout'

  - name: install statically linked docker
    shell: cp /tmp/docker/* /usr/bin/
    become: true
    when: '"not a dynamic executable" not in docker_ldd.stdout'

  - name: start the docker daemon
    service:
      name: docker
      state: started
    become: true
