- hosts: all
  vars:
    mem: 512M
    period: 50000
    fldr: "{{ansible_env.HOME}}/var/porta/base-vs-limited-targets"
    skip_base: true
    cpus: "0"
    repetitions: [1]
    cmds: ['docker', './porta']
  pre_tasks:
  - name: Assert preconditions
    assert:
      that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_lsb.major_release|int >= 12"
      - "('3.13' in ansible_kernel or '3.15' in ansible_kernel or '3.19' in ansible_kernel)"
      - "'base' in groups"
      - "'targets' in groups"
      - "groups.base|length == 1"
      - "groups.targets|length > 0"
      - "benchmarks is defined"
  - name: Get jq version
    local_action: command jq --version
    register: jq_version
    sudo: false
  - name: Check jq version
    local_action: fail msg='Incorrect jq version (expecting 1.5)'
    when: "'1.5' not in jq_version.stdout"
    sudo: false

  tasks:
# setup
  - name: delete previous results
    file: path={{fldr}} state=absent
    ignore_errors: true
  - name: install linux linux-headers
    package: name=linux-headers-{{ ansible_kernel }} state=present
  - name: create test folder
    file: path={{fldr}}/tests state=directory mode=0755
  - name: create test folder locally
    local_action: file path=tests state=directory mode=0755
    sudo: false
  - name: send porta
    copy: src=porta dest={{fldr}} mode=0755
  - name: pull porta image
    command: docker pull ivotron/porta

# send parameters to targets
  - name: check if parameters.json file exists locally
    local_action: stat path="parameters/{{item}}.json"
    register: "{{item}}_params.stat.exists"
    with_items: groups.targets
    sudo: false
  - name: fail if file for there are no parameters for a target
    local_action: fail "msg=Cannot find parameters file for {{item}}"
    when: not "{{item}}_params.stat.exists and {{item}} in groups.targets"
    with_items: groups.targets
  - name: Send parameters file
    copy: src=parameters/{{inventory_hostname}}.json dest={{fldr}}/parameters.json mode=0644
    when: inventory_hostname in groups.targets

# execute test benchmarks
  - name: pull benchmark images
    command: docker pull {{ item }}
    with_items: benchmarks
  - name: execute testing benchmarks
    command: {{item[0]}} run --rm --memory={{mem}} --memory-swap={{mem}} --cpuset-cpus={{cpus}} {{item[1]}} > "{{fldr}}/tests/{{item[1].replace('/','_')}}_{{item[0].replace('./','')}}_{{item[2]}}.json"
    with_nested:
    - cmds
    - benchmarks
    - repetitions
    when: inventory_hostname in groups.targets or (inventory_hostname in groups.base and not skip_base|bool and 'docker' in item[0])

# fetch results
  - name: compress tests folder
    command: tar cvfj tests.bz2 tests chdir={{fldr}}
  - name: get result tar balls
    fetch: src={{fldr}}/tests.bz2 dest=tests/{{inventory_hostname}}.bz2 flat=yes
  - name: uncompress locally
    local_action: command ./uncompress
    sudo: false

# postprocess on localhost
  - name: merge results
    local_action: command ./merge_results
    sudo: false
  - name: obtain normalized results
    local_action: command docker run --rm -v `pwd`:/data --entrypoint=/data/normalize.py ivotron/jupyter-pd-mpl-h5 {{ item }}
    sudo: false
    with_items: groups.base
    when: not skip_base|bool

# store facts
  - name: create facts folder
    local_action: file path=facts state=directory mode=0755
    sudo: false
  - name: store facts about remotes
    local_action: copy content="{{ hostvars[item] | to_nice_json }}" dest=./facts/{{ item }}.json
    sudo: false
    with_items: groups['all']
