---
- hosts: all
  tasks:

# check preconditions
  - include: ../common/check_preconditions.yml

  - name: check if base.json file exists locally
    local_action:
      module: stat
      path: base.json
    run_once: true
    register: basefile
    failed_when: not basefile.stat.exists

  - name: create result parameters folder if it don't exist
    local_action:
      module: file
      path: ./parameters
      state: directory
      mode: 0755
    run_once: true

# tune targets
  - name: pull torpor image
    shell: docker pull ivotron/torpor

  - name: download torpor script
    get_url:
      url: https://raw.githubusercontent.com/ivotron/torpor/master/torpor
      dest: ./torpor
      mode: 0755

  - name: push base.json to targets
    copy:
      src: ./base.json
      dest: ./base.json
      mode: 0644

  - name: tune system
    shell: ./torpor {{ torpor_flags }}

# get results
  - name: fetch parameter files
    fetch:
      src: ./parameters.json
      dest: ./parameters/{{inventory_hostname}}.json
      flat: true
    # TODO: merge parameters in a single ./parameters.json file

  - name: fetch torpor log
    fetch:
      src: ./torpor.log
      dest: ./parameters/{{inventory_hostname}}_torpor.log
      flat: yes

  - include: ../common/store_facts.yml
