- hosts: all
  vars:
    install_docker: no
  pre_tasks:
  - name: assert preconditions
    assert:
      that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_lsb.major_release|int >= 12"
      - "ansible_kernel | version_compare('4.0', '<')"
      - "benchmarks is defined"
  - name: alter grub file to allow swap limits
    lineinfile:
      dest: /etc/default/grub
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'
    register: grubfile
  - name: update grub
    command: update-grub
    when: grubfile|changed
  - name: restart machine
    command: reboot
    async: 0
    poll: 0
    ignore_errors: true
    when: grubfile|changed
  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started
    sudo: false
    when: grubfile|changed

  roles:
  - role: angstwad.docker_ubuntu
    when:
    - install_docker|bool

  tasks:

# setup
  - name: install jq
    apt: name=jq state=present
  - name: create folders
    file: path=/tmp/mica/tests state=directory mode=0755
  - name: send mica files
    copy: src={{ item }} dest=/tmp/mica/{{ item }} mode=0755
    with_items:
      - profile
      - entrypoint_for_profiling.sh

# profile
  - name: execute profiling
    command: ./profile {{ item }} chdir=/tmp/mica
    with_items: benchmarks
  - name: retrieve profiles
    fetch: src=/tmp/mica/output.csv dest=output.csv mode=0644
