#!/bin/bash

usage() { echo "Usage: $0 -i <image> -f <run-flags> -c <command> -n <name> -p <pre-command> ]" 1>&2; exit 1; }

while getopts ":f:i:n:c:p:w:" o; do
  case "${o}" in
    i)
      image=${OPTARG}
      ;;
    n)
      name=${OPTARG}
      ;;
    f)
      flags=${OPTARG}
      ;;
    c)
      cmd=${OPTARG}
      ;;
    p)
      pre=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "$image" ] ; then
  echo "Expecting image name in -i"
  exit 1
fi
if [ -z "$cmd" ] ; then
  echo "Expecting command with -c"
  exit 1
fi

# TODO check versions for all dependencies

docker info &> /dev/null
if [ $? -ne 0 ] ; then
  echo "Unable to invoke docker"
  exit 1
fi

jq --version &> /dev/null
if [ $? -ne 0 ] ; then
  echo "Unable to invoke jq"
  exit 1
fi

cwd=$PWD

# attempt to install mica if it doesn't exist
if [ ! -d `pwd`/pin/source/tools/mica ] ; then
  echo "Unable to find mica folder. Will attempt to install it now."

  docker run --rm -v `pwd`:/mnt ivotron/mica

  if [ ! -d `pwd`/pin/source/tools/mica ] ; then
    echo "Unable to install mica."
    exit 1
  fi

  cd pin/source/tools/mica
  cp mica.conf.example mica.conf
  sed -i -e 's/ilp_one/all/' mica.conf
  sed -i -e 's/itypes_spec_file.*/itypes_spec_file: \/pin\/source\/tools\/mica\/itypes_default.spec/' mica.conf
fi

cd $cwd

# pull image explicitly
docker pull $image &> /dev/null

# check for dependencies inside container
for p in gcc g++ make ; do
  docker run --rm --entrypoint=/bin/bash $image -c "$p -v" &> /dev/null
  if [ $? -ne 0 ] ; then
    echo "Unable to find $p in given container"
    exit 1
  fi
done

docker kill $name &> /dev/null
docker rm $name &> /dev/null

echo "profiling $name"

docker run --rm \
  -v `pwd`/entrypoint_for_profiling.sh:/root/entrypoint_for_profiling.sh \
  -v `pwd`/pin:/pin \
  -e PRE="$pre" \
  -e CMD="$cmd" \
  --privileged \
  --entrypoint=/root/entrypoint_for_profiling.sh \
  $flags $image &> /tmp/error

if [ $? -ne 0 ] ; then
  echo "Error while executing $image"
  cat /tmp/error
  exit 1
fi

if [ ! -f output.csv ] ; then
  csvheader="container,process,"
  csvheader+="instruction_cnt,"
  csvheader+="ilp_cycle_count_win_size_32,"
  csvheader+="ilp_cycle_count_win_size_64,"
  csvheader+="ilp_cycle_count_win_size_128,"
  csvheader+="ilp_cycle_count_win_size_256,"
  csvheader+="itypes_instruction_cnt,"
  csvheader+="itypes_mem_read_cnt,"
  csvheader+="itypes_mem_write_cnt,"
  csvheader+="itypes_control_cnt,"
  csvheader+="itypes_arith_cnt,"
  csvheader+="itypes_fp_cnt,"
  csvheader+="itypes_stack_cnt,"
  csvheader+="itypes_shift_cnt,"
  csvheader+="itypes_string_cnt,"
  csvheader+="itypes_sse_cnt,"
  csvheader+="itypes_system_cnt,"
  csvheader+="itypes_nop_cnt,"
  csvheader+="itypes_other_cnt,"
  csvheader+="ppm_instruction_cnt,"
  csvheader+="ppm_GAg_mispred_cnt_4bits,"
  csvheader+="ppm_PAg_mispred_cnt_4bits,"
  csvheader+="ppm_GAs_mispred_cnt_4bits,"
  csvheader+="ppm_PAs_mispred_cnt_4bits,"
  csvheader+="ppm_GAg_mispred_cnt_8bits,"
  csvheader+="ppm_PAg_mispred_cnt_8bits,"
  csvheader+="ppm_GAs_mispred_cnt_8bits,"
  csvheader+="ppm_PAs_mispred_cnt_8bits,"
  csvheader+="ppm_GAg_mispred_cnt_12bits,"
  csvheader+="ppm_PAg_mispred_cnt_12bits,"
  csvheader+="ppm_GAs_mispred_cnt_12bits,"
  csvheader+="ppm_PAs_mispred_cnt_12bits,"
  csvheader+="reg_total_reg_use_cnt,"
  csvheader+="reg_total_reg_age,"
  csvheader+="reg_reg_age_cnt_1,"
  csvheader+="reg_reg_age_cnt_2,"
  csvheader+="reg_reg_age_cnt_4,"
  csvheader+="reg_reg_age_cnt_8,"
  csvheader+="reg_reg_age_cnt_16,"
  csvheader+="reg_reg_age_cnt_32,"
  csvheader+="reg_reg_age_cnt_64,"
  csvheader+="stride_mem_read_cnt,"
  csvheader+="stride_mem_read_local_stride_0,"
  csvheader+="stride_mem_read_local_stride_8,"
  csvheader+="stride_mem_read_local_stride_64,"
  csvheader+="stride_mem_read_local_stride_512,"
  csvheader+="stride_mem_read_local_stride_4096,"
  csvheader+="stride_mem_read_local_stride_32768,"
  csvheader+="stride_mem_read_local_stride_262144,"
  csvheader+="stride_mem_read_global_stride_0,"
  csvheader+="stride_mem_read_global_stride_8,"
  csvheader+="stride_mem_read_global_stride_64,"
  csvheader+="stride_mem_read_global_stride_512,"
  csvheader+="stride_mem_read_global_stride_4096,"
  csvheader+="stride_mem_read_global_stride_32768,"
  csvheader+="stride_mem_read_global_stride_262144,"
  csvheader+="stride_mem_write_cnt,"
  csvheader+="stride_mem_write_local_stride_0,"
  csvheader+="stride_mem_write_local_stride_8,"
  csvheader+="stride_mem_write_local_stride_64,"
  csvheader+="stride_mem_write_local_stride_512,"
  csvheader+="stride_mem_write_local_stride_4096,"
  csvheader+="stride_mem_write_local_stride_32768,"
  csvheader+="stride_mem_write_local_stride_262144,"
  csvheader+="stride_mem_write_global_stride_0,"
  csvheader+="stride_mem_write_global_stride_8,"
  csvheader+="stride_mem_write_global_stride_64,"
  csvheader+="stride_mem_write_global_stride_512,"
  csvheader+="stride_mem_write_global_stride_4096,"
  csvheader+="stride_mem_write_global_stride_32768,"
  csvheader+="stride_mem_write_global_stride_262144,"
  csvheader+="memfootprint_num_64-byte_blocks_data,"
  csvheader+="memfootprint_num_4KB_pages_data,"
  csvheader+="memfootprint_num_64-byte_blocks_instr,"
  csvheader+="memfootprint_num_4KB_pages_instr,"
  csvheader+="memstackdist_mem_access_cnt,"
  csvheader+="memstackdist_cold_ref_cnt,"
  csvheader+="memstackdist_acc_cnt_2^0-2^1,"
  csvheader+="memstackdist_acc_cnt_2^1-2^2,"
  csvheader+="memstackdist_acc_cnt_2^2-2^3,"
  csvheader+="memstackdist_acc_cnt_2^3-2^4,"
  csvheader+="memstackdist_acc_cnt_2^4-2^5,"
  csvheader+="memstackdist_acc_cnt_2^5-2^6,"
  csvheader+="memstackdist_acc_cnt_2^6-2^7,"
  csvheader+="memstackdist_acc_cnt_2^7-2^8,"
  csvheader+="memstackdist_acc_cnt_2^8-2^9,"
  csvheader+="memstackdist_acc_cnt_2^9-2^10,"
  csvheader+="memstackdist_acc_cnt_2^10-2^11,"
  csvheader+="memstackdist_acc_cnt_2^11-2^12,"
  csvheader+="memstackdist_acc_cnt_2^12-2^13,"
  csvheader+="memstackdist_acc_cnt_2^13-2^14,"
  csvheader+="memstackdist_acc_cnt_2^14-2^15,"
  csvheader+="memstackdist_acc_cnt_2^15-2^16,"
  csvheader+="memstackdist_acc_cnt_2^16-2^17,"
  csvheader+="memstackdist_acc_cnt_2^17-2^18,"
  csvheader+="memstackdist_acc_cnt_over_2^18"
  echo $csvheader > output.csv
fi

# get number of processes (by getting the num of files that got generated)
num_procs=`ls pin/source/tools/mica/ilp_full_int_*.out | wc -l`

echo "" > ${name}.tsv
for p in `seq 0 $((num_procs-1))` ; do
  printf "${name},${p}," >> output.csv
  printf "process: $p" >> ${name}.tsv

  for atype in ilp itypes ppm reg stride memfootprint memreusedist ; do
    files=`ls pin/source/tools/mica/${atype}_full_int_*.out`
    file="${files[$((p))]}"

    line=$(head -n 1 $file)
    line=`echo $line | sed 's/ /,/g'`

    printf "$line" >> output.csv
    cat $file >> ${name}.tsv
  done
  printf "\n" >> output.csv
done
