cadvisor:
  image: google/cadvisor:0.16.0
  cpuset: 2,3
  ports:
    - "9090:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxdb
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086

influxdb:
  image: tutum/influxdb:0.8.8
  cpuset: 2,3
  volumes:
    - ./influxdb:/data
  ports:
    - 8083:8083 # Admin Site
    - 8086:8086 # API
  environment:
    # Extra auto-create magic provided by this image
    PRE_CREATE_DB: "cadvisor;metrics"
