- hosts: all
  vars:
    install_docker: no

  pre_tasks:
  - name: Assert preconditions
    assert:
      that:
      - "benchmarks is defined"
      - "mem_quotas is defined"
      - "cpu_periods is defined"
      - "cpu_quotas is defined"

  roles:
  - requirements

  tasks:
  - name: delete previous results
    file: path=/tmp/porta/ state=absent
  - name: create results folder
    file: path=/tmp/porta/tests state=directory mode=0755
  - name: send cadvisor/influxdb compose file
    copy: src=../docker/cadvisor/docker-compose.yml dest=/tmp/porta/docker-compose.yml mode=0755

  - name: start cadvisor
    command: docker-compose up --force-recreate -d chdir=/tmp/porta

  - name: pull porta image
    command: docker pull ivotron/porta
  - name: pull benchmark images
    command: docker pull {{ item }}
    with_items: benchmarks
  - name: run benchmarks

    shell: docker run --rm --privileged --entrypoint=/usr/bin/docker-run-wrapper -v /sys/kernel/debug:/sys/kernel/debug -v /usr/src:/usr/src -v /lib/modules:/lib/modules -v `which docker`:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock {{ item[0] }} --name {{ item[3] }}_{{ item[0] }}_{{ item[1] }}_{{ item[2] }} --cpu-period={{ item[1] }} --cpu-quota={{ item[2] }} --rm --cpuset-cpus=0 --memory=512M --memory-swap=512M {{ item[3] }} > tests/{{ item[3] }}_{{ item[0] }}_{{ item[1] }}_{{ item[2] }}.json chdir=/tmp/porta
    with_items:
    - {{ mem_quotas }}
    - {{ cpu_periods }}
    - {{ cpu_quotas }}
    - {{ benchmarks }}

  - name: stop cadvisor
    command: docker-compose stop
  - name: compress influxdb data
    command: tar cvfj influxdb.bz2 influxdb chdir=/tmp/porta
  - name: compress tests folder
    command: tar cvfj tests.bz2 tests chdir=/tmp/porta

# get results
  - name: get influxdb data
    fetch: src=/tmp/porta/influxdb.bz2 dest=influxdb.bz2
  - name: get tests data
    fetch: src=/tmp/porta/tests.bz2 dest=tests.bz2
